import * as fs from "fs";
import * as path from "path";

/**
 * Reads compiled Hardhat artifacts and writes ABI + address stubs
 * to packages/web/lib/contracts.ts for frontend consumption.
 *
 * Usage: npx ts-node scripts/export-abi.ts
 */

const ARTIFACTS_DIR = path.join(__dirname, "..", "artifacts", "contracts");
const OUTPUT_FILE = path.join(__dirname, "..", "..", "web", "lib", "contracts.ts");

function readAbi(contractPath: string, contractName: string): unknown[] {
  const jsonPath = path.join(ARTIFACTS_DIR, contractPath, `${contractName}.json`);
  const raw = JSON.parse(fs.readFileSync(jsonPath, "utf-8"));
  return raw.abi;
}

function main() {
  const marketAbi = readAbi("Market.sol", "Market");
  const factoryAbi = readAbi("MarketFactory.sol", "MarketFactory");

  const output = `// Auto-generated by scripts/export-abi.ts — do not edit manually.
// Re-run: cd packages/contracts && npx ts-node scripts/export-abi.ts

export const MARKET_FACTORY_ADDRESS = '0x0000000000000000000000000000000000000000' as \`0x\${string}\` // TODO: update after deployment

export const MARKET_FACTORY_ABI = ${JSON.stringify(factoryAbi, null, 2)} as const

export const MARKET_ABI = ${JSON.stringify(marketAbi, null, 2)} as const

export const ERC20_ABI = [
  {
    type: 'function',
    name: 'approve',
    inputs: [
      { name: 'spender', type: 'address' },
      { name: 'amount', type: 'uint256' },
    ],
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'balanceOf',
    inputs: [{ name: 'account', type: 'address' }],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'allowance',
    inputs: [
      { name: 'owner', type: 'address' },
      { name: 'spender', type: 'address' },
    ],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'decimals',
    inputs: [],
    outputs: [{ name: '', type: 'uint8' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'transfer',
    inputs: [
      { name: 'to', type: 'address' },
      { name: 'amount', type: 'uint256' },
    ],
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'nonpayable',
  },
] as const
`;

  fs.writeFileSync(OUTPUT_FILE, output, "utf-8");
  console.log(`ABIs exported to ${OUTPUT_FILE}`);
  console.log(`  MARKET_FACTORY_ABI: ${factoryAbi.length} entries`);
  console.log(`  MARKET_ABI: ${marketAbi.length} entries`);
}

main();
